version: '3.9'

services:
  backend:
    build: .
    container_name: voomly-backend
    user: root
    ports:
      - "3002:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./cloned_repos:/usr/src/app/cloned_repos
      - /etc/nginx/sites-available:/nginx/sites-available
      - /etc/nginx/sites-enabled:/nginx/sites-enabled
    environment:
      - NODE_ENV=development
